#ifndef X11_INTERNAL_H
#define X11_INTERNAL_H

#include "kernel/gui/x11.h"

extern struct X11_CONN conns[X11_MAX_CONNS];
extern uint32_t xid_next, gid_next, pid_next, atom_next;

gfx_color pix_to_color(uint32_t pixel);
int gc_fg(struct X11_CONN *c, uint32_t gid, gfx_color *out);
int gc_idx(struct X11_CONN *c, uint32_t gid);
int owner_of(struct WL_SURFACE *s, struct X11_CONN **out, struct X11_WINDOW **wout);
int pix_idx(struct X11_CONN *c, uint32_t pid);
int trig_cos(int deg);
int trig_sin(int deg);
int win_idx(struct X11_CONN *c, uint32_t xid);
int win_realize(struct X11_CONN *c, int i);
int16_t clo16(int v);
struct X11_DRAW draw_get(struct X11_CONN *c, uint32_t id);
uint16_t rd16(const uint8_t *p);
uint32_t atom_intern(struct X11_CONN *c, const char *name, int len, int only_if_exists, int *found);
uint32_t rd32(const uint8_t *p);
void draw_commit(struct X11_CONN *c, uint32_t id);
void draw_line(struct GFX_CANVAS *cv, int x0, int y0, int x1, int y1, gfx_color col);
void h_alloc_color(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_alloc_named_color(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_change_attrs(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_change_gc(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_change_property(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_clear_area(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_configure_window(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_copy_area(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_create_gc(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_create_pixmap(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_create_window(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_delete_property(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_destroy_window(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_fill_poly(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_free_gc(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_free_pixmap(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_get_geometry(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_get_image(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_get_input_focus(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_get_property(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_get_window_attrs(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_intern_atom(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_list_extensions(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_lookup_color(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_map_window(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_open_font(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_poly_arc(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_poly_fill_arc(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_poly_fill_rect(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_poly_line(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_poly_point(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_poly_rectangle(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_poly_segment(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_put_image(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_query_colors(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_query_extension(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_query_pointer(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_query_text_extents(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_query_tree(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_set_input_focus(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_translate_coords(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_unmap_window(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void post_event_to(struct X11_CONN *c, struct X11_WINDOW *w, const uint8_t *ev, uint32_t mask_bit);
void win_teardown(struct X11_CONN *c, int i);
void wr16(uint8_t *p, uint16_t v);
void wr32(uint8_t *p, uint32_t v);
void x11_notify_button(struct WL_SURFACE *s, int x, int y, int button, int pressed);
void x11_notify_key(struct WL_SURFACE *s, int keycode, int pressed, int mods);
void x11_notify_motion(struct WL_SURFACE *s, int x, int y);

gfx_color pix_to_color(uint32_t pixel);
int out_bytes(struct X11_CONN *c, const void *p, uint32_t n);
int pix_idx(struct X11_CONN *c, uint32_t pid);
int win_idx(struct X11_CONN *c, uint32_t xid);
int x11_conn_feed(struct X11_CONN *c, const uint8_t *data, uint32_t len);
int16_t clo16(int v);
struct X11_CONN *x11_conn_open(void);
uint16_t rd16(const uint8_t *p);
uint32_t rd32(const uint8_t *p);
uint32_t x11_conn_drain(struct X11_CONN *c, uint8_t *buf, uint32_t len);
void h_alloc_color(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_alloc_named_color(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_change_attrs(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_change_gc(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_change_property(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_clear_area(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_configure_window(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_copy_area(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_create_gc(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_create_pixmap(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_create_window(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_delete_property(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_destroy_window(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_fill_poly(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_free_gc(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_free_pixmap(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_get_geometry(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_get_image(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_get_input_focus(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_get_property(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_get_window_attrs(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_intern_atom(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_list_extensions(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_lookup_color(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_map_window(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_open_font(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_poly_arc(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_poly_fill_arc(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_poly_fill_rect(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_poly_line(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_poly_point(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_poly_rectangle(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_poly_segment(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_put_image(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_query_colors(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_query_extension(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_query_pointer(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_query_text_extents(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_query_tree(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_set_input_focus(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_translate_coords(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void h_unmap_window(struct X11_CONN *c, const uint8_t *p, uint32_t len);
void out_event(struct X11_CONN *c, const uint8_t *ev);
void post_error(struct X11_CONN *c, uint8_t code, uint8_t major, uint16_t minor, uint32_t res);
void post_event_to(struct X11_CONN *c, struct X11_WINDOW *w, const uint8_t *ev, uint32_t mask_bit);
void reply_finish(struct X11_CONN *c, const uint8_t *head, const uint8_t *extra, uint32_t n);
void reply_init(struct X11_CONN *c, uint8_t major, uint32_t extra, uint8_t *head);
void wr16(uint8_t *p, uint16_t v);
void wr32(uint8_t *p, uint32_t v);
void x11_conn_close(struct X11_CONN *c);

#endif
